version: '3.8'

services:
  user-service:
    build:
      context: ../
      dockerfile: ./cmd/user/Dockerfile
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=myproject
      - DB_PORT=5434
    ports:
      - 50051:50051
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myproject
    volumes:
      - ../scripts/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5434:5432

